### PR TITLE
Adding docker support

### PR DESCRIPTION
**Pull request by Maescool**
This will add docker support to the repository
Docker is a modern way to build, run and distribute applications in an easy way.
more info regarding using docker: https://www.docker.com/

### CODE REVIEW

**Comment by JamieSinn** [comment]
Now this is a cool addon. Maybe make it non required? Not everyone has a docker env set up and ready.
:+1:

**Comment by Ichbinjoe** [comment]
Doesn't seem required. :+1:. I would make the README.md changes in a different commit.

**Comment by Maescool** [comment]
It isn't required, just makes it easier for the people who have it set up, to run it in a clean easy way.
I do see a lot of people starting to switch to this system, just my small contribution to show people this is a thing that is happening in the industry

**Comment by Vilsol** [comment]
Definitely support this, would make a lot of things easier, but I would also want to make it possible to control the container server.properties file using environment variables. :+1:

**Comment by HeroCC** [comment]
What @Vilsol said, :+1:

**Comment by RoboMWM** [comment]
Only thing is Aikar might not agree with them GC choices but otherwise am ambivalent to this.

**Comment by Ichbinjoe** [comment]
This isn't a production server. I would argue the GC issues don't actually matter. I am personally curious why there are so many GC args within this. I think we should keep it as ambiguous, and really only have max memory and jar flags.

**Comment by md-5** [comment]
No, we're not using docker

**Comment by Vilsol** [comment]
@md-5 Any descriptive reason of why not?

**Comment by md-5** [comment]
Because there is no reason for us to run the server in a container.

**Pull request closed without merging**
