### PR TITLE
Adding TitleManager

### PR DESCRIPTION
**Pull request by Puharesource**
This update adds TitleManager to the server and brings the following features:
- SpigotCraft above the `TAB` menu.
- A "beam" animation and the amount of players currently online, below the `TAB` menu.
- A welcome message whenever the player joins the server.

Here's some images:
The welcome image: https://i.puha.io/151112102536.png
The `TAB` menu: https://i.puha.io/151112103708.png (The orange dashes are the beams moving back and forth)

https://www.spigotmc.org/resources/titlemanager.1049/

### CODE REVIEW

**Comment by md-5** [comment]
:-1: no need

**Comment by Puharesource** [comment]
The welcome message could very well be removed, however, I find it extremely useful to see the amount of players currently online on the server, simply by holding down `TAB` (If there's too many to could in a split second of course). (But again that's my opinion :P)

**Comment by Cldfire** [comment]
We should just use Maxim's TAB and AnimatedNames plugins.

**Comment by JamieSinn** [comment]
:-1: No need, just a fancy addon.

**Comment by RoboMWM** [comment]
I'm not a fan of tablist editors... especially those that add unnecessary visuals like those "beams" :-1:

**Comment by Cldfire** [comment]
Hey, it's helpful to have the IP on TAB...

**Comment by HappyHarm** [comment]
:+1: Think if you create a server SpigotCraft you could also show some of the possibilities. I think this is an easy to implement feature what makes the server some nicer. And what @Cldfire already said, a tab ip is helpful :P

**Comment by md-5** [comment]
Also, if this plugin needs NMS we can't use it, since the server will be running snapshots.

**Comment by Puharesource** [comment]
Unfortunately it does.

(I would be more than willing to update it for each snapshot though)

**Pull request closed without merging**
