### PR TITLE
Add custom essentials locale file / change some things in Essentials config

### PR DESCRIPTION
**Pull request by Cldfire**
Adds the essentials locale file so that messages / message colors can be edited. 

Also changed primary message color to '&e' / secondary message color to '&6' (matches Spigot theme better) and edited quite a few messages to fix grammar / make them more user friendly.

Also made some changes to the essentials config (meant to make a seperate PR, still new to Github, sorry :/).

I saw that the basic essentials config PR was denied, but it does need some changes, so I'm submitting this PR with them here.

This removes the first-join kit, sets the starting spawnpoint to the spawnpoint of the world, changes the first-join message to something that matches the chat theme, changes the chat format to something more visually appealing, disables economy overdrafting, sets tpa-accept-cancellation to 60 instead of 120, adds easily recallable home permissions (essentials.sethome.multiple.[two through twenty]), adds custom join / quit messages that match the theme, sets auto-AFK-kick to 15 minutes instead of 5, enables per-warp permissions and enables permission-based-item-spawn.

All settings changed are strictly necessary. No other settings have been touched.

### CODE REVIEW

**Comment by ctian1** [comment]
:+1: after syntax fixes

**Comment by Cldfire** [comment]
Syntax has been fixed (thanks for catching it pangeacake).

**Comment by RoboMWM** [comment]
PR'd changes to afk status messages: https://github.com/Cldfire/SpigotCraft/pull/2

> Why not remove afk feature in config.yml?

Afk feature provides idle kicking, letting players who /msg know that the player is afk, and showing up as afk in /list. Clearing its message in this file simply stops the "player is afk/player has returned" statuses sent in chat.

**Comment by ctian1** [comment]
@RoboMWM, why not disable those messages in Essentials config instead?

**Comment by RoboMWM** [comment]
Don't think it's possible to just disable the messages it sends in config. I'd be interested if there is a way..? (I remember trying to find this before.)

**Comment by ctian1** [comment]
@RoboMWM nevermind.. thought there was a way for some reason, I thought I had used it before but nope, nevermind

**Comment by RoboMWM** [comment]
:+1:

**Comment by HappyHarm** [comment]
:+1:

**Comment by RoboMWM** [comment]
Do we need per-warp permissions? Can't imagine a need for that...

**Comment by Cldfire** [comment]
@RoboMWM what if we want certain warps for staff and certain warps for normal players? Or maybe we don't want people who are greylisted to be able to use certain warps.

Better to have it on and have the option (you can always just grant essentials.warps.\* if you want someone to have access to all warps, so it's not like it makes much of a difference).

**Comment by RoboMWM** [comment]
If PR #53 is merged, then I do agree with per-warp permissions, and would have to apply permissions per-world for warps in the same world only.

**Comment by Cldfire** [comment]
@RoboMWM that's a good point. Changing now.

**Comment by ghost** [comment]
:+1:

**Pull request closed without merging**
