### PR TITLE
WildernessTp added to test with 1.9

### PR DESCRIPTION
**Pull request by Qballl**

### CODE REVIEW

**Comment by Qballl** [comment]
Want to test my wild teleportation plugin with 1.9 to make sure it will work sorry about the title

**Comment by HeroCC** [comment]
What does Wilderness TP do?

**Comment by Qballl** [comment]
It is a plugin like randomtp on command it will teleport the player to a random location here is more info my spigot post https://www.spigotmc.org/resources/wildernesstp.18431/

**Comment by plengyel1** [comment]
:+1:

**Comment by misterT2525** [comment]
:-1:

**Comment by Qballl** [comment]
:( why the thumbs down

**Comment by misterT2525** [comment]
It is a buggy plugin.

**Comment by Qballl** [comment]
How is it buggy I know the only bug i have found is chunk load lag which Im trying my hardest to fix. Right now my main concern is making sure it will work with 1.9 and then fix that chunk load lag

**Comment by misterT2525** [comment]
It throw `java.lang.ClassCastException` when i execute `wild` command from console.

**Comment by Qballl** [comment]
Oh hmm I thought I made it to where /wild [player] worked thanks for that info will test and fix and then may reupload it here if it hasnt been approved/disapproved by then

**Comment by Qballl** [comment]
But besides that any other reason for the thumbs down. I really want this approved so I can test it before 1.9 official release

**Comment by RoboMWM** [comment]
If this isn't using 1.9 stuff, there's no need to test API we know that works well. :-1:

**Comment by Qballl** [comment]
Wasnt sure if it used anything that 1.9 changed

**Comment by rmarmorstein** [comment]
:+1:

**Comment by picknchew** [comment]
:-1: pointless and unneeded on the server. We're not trying to get members as far away as we can.

**Comment by Qballl** [comment]
Like I had mentioned I just wanted to test my plugin to be 100% sure it would work with 1.9 as is

**Comment by picknchew** [comment]
The server isn't for your own plugin testing either. You can test it when it comes out.

**Comment by RoboMWM** [comment]
> The server isn't for your own plugin testing either. You can test it when it comes out.

Basically that. This server is more for testing Spigot itself, not necessarily its plugins - especially when this doesn't use 1.9 stuff or things like event handlers and the like

**Comment by Qballl** [comment]
ok

**Pull request closed without merging**
