### PR TITLE
Update config.yml

### PR DESCRIPTION
**Pull request by DoNotSpamPls**
Changes made: 
- Changes OPs color
- Removed nickname prefix
- Longer max-nick-length
- Teleport delay, cooldown and invulnerability are now 1 second
- /spawnmob limited to 1 mob
- Edited kits
- Removed Admins grouping
- Set auto-afk-kick to 1800 seconds (10 minutes)
- Disabled item pickup while AFK
- Edited custom join/quit messages
- Enabled unsafe enchantments
- Set max walk/fly speed to 1.0
- Set max-tempban-time to 86400 seconds (1 day)
- Gived 5 max homes to default rank
- Starting balance is now $500
- Removed loans
- Made a cool chat format
- Edited announce-format when players join for the first time
- Set spawnpoint to none
- Set kit to ' '

Phew, a lot of changes. Most of you will not even read them all :D

### CODE REVIEW

**Comment by DoNotSpamPls** [comment]
#bump

**Comment by TomLewis** [comment]
Starting Balance is too high.

**Comment by Cldfire** [comment]
Good luck getting this pulled, my config PR has been sitting out there for over a month ._.

**Comment by DoNotSpamPls** [comment]
@FrozenBeard changed start balance to 150 :)
@Cldfire maybe the essentials config isn't that important :/

**Comment by RoboMWM** [comment]
> maybe the essentials config isn't that important

Is there even a reason to have Essentials money?

**Comment by DoNotSpamPls** [comment]
idk

**Comment by DoNotSpamPls** [comment]
This doesn't seem to be approved
#Close

**Pull request closed without merging**
