### PR TITLE
Format chat

### PR DESCRIPTION
**Pull request by Yamakaja**
The chat can get pretty unreadable in its current state, this PR should clean that up

### CODE REVIEW

**Comment by md-5** [comment]
Whats the point in display names ending in &7?

**Comment by sweepies** [comment]
I think adding an edgy unicode character would do the opposite of cleaning up the chat.

**Comment by MiniDigger** [comment]
the & 7 changes the color of the actual message. 

what's getting cleared up here is not bring able to read messages from ppl with the default group (they have no prefix). it's also hard to separate auto messages and chat messages. separating them via color makes it easier to not read them while in a conversation.

**Comment by ScruffyRules** [comment]
I just gave default a prefix
image

**Comment by Yamakaja** [comment]
No, the prefix ends in &7, this makes the players name appear grey. Then you have a » in dark grey and then an &f for a white message. Look at the essentials config

**Comment by MartenM** [comment]
I actually agree with this. In the limited time that I was on the server I found it pretty hard to seperate the names an actual messages.

This a pretty old PR but it still annoying to read the chat in the current state.

**Comment by ScruffyRules** [comment]
I could make defaults have the grey colour and etc

**Pull request closed without merging**
