### PR TITLE
Implement a light loading YAML system.

### PR DESCRIPTION
**Pull request by PizzaCrust**
This pull requests includes a LightLoading plugin that installs plugins from install YAMLs from /plugins  
This allows the repository to be more lightweight than with the JARs. (plugin allows downloading maven artifacts)

The link to the Spigot resource page is here: https://www.spigotmc.org/resources/lightloading.15405/

### CODE REVIEW

**Comment by TomLewis** [comment]
This sounds interesting, can you please link us to the Project page for the LightLoading plugin.

**Comment by PizzaCrust** [comment]
Just edited the post to include the spigot resource.

**Comment by HeroCC** [comment]
:-1: Interesting concept, but I don't think it is needed for this server

**Comment by PizzaCrust** [comment]
It does not help the server in any performance, but allows easier contributions via plugin install files.

**Comment by ctian1** [comment]
Still seems unneeded.. including the plugin files is fine and we need to include the configuration setups anyways.

**Comment by PizzaCrust** [comment]
Configuration folder is needed, but it still allows fast cloning for contributors.

**Comment by Ichbinjoe** [comment]
The clone speed is marginal, matched with the fact that the plugins will be
downloaded regardless. :-1:

**Comment by PizzaCrust** [comment]
But, why not?

**Comment by md-5** [comment]
Unnecessary

**Pull request closed without merging**
