### PR TITLE
[Joke] Fixed horrible oversight in permissions file

### PR DESCRIPTION
**Pull request by masterdoctor**
You know you want to ;)

### CODE REVIEW

**Comment by wyatt-herkamp** [comment]
No!

**Comment by masterdoctor** [comment]
@wherkamp please?

**Comment by Banbeucmas** [comment]
We can have the Lit prefix, it's lit anyway

**Comment by masterdoctor** [comment]
Worth a shot lol 😄

**Comment by MiniDigger** [comment]
instead of slowing down the development and testing of spigot 1.13 by creating useless PRs, why don't you hop on the server an search for bugs like the rest is doing?

**Comment by wyatt-herkamp** [comment]
+1 @MiniDigger 
*He was*

**Comment by masterdoctor** [comment]
Ouch @MiniDigger - but reasonable.

**Pull request closed without merging**
