### PR TITLE
Add FAQ Plugin

### PR DESCRIPTION
**Pull request by ghost**
I suggest that you add this neat FAQ plugin to help answer players questions. I have used it on my server, and seem it on others... Its great!
https://www.spigotmc.org/resources/faq-frequently-asked-questions-1-8.11402/

### CODE REVIEW

**Comment by Saphiria** [comment]
:+1:

**Comment by RoboMWM** [comment]
Uh looks like you committed a blank file, and why not Essentials info.txt?

**Comment by ctian1** [comment]
Do we really need this? if we already have the IRC bridge and forum support

**Comment by Cldfire** [comment]
:+1:

RoboMWM FAQ works far better than essentials /info, take a look at it

**Comment by JamieSinn** [comment]
:+1:

**Comment by JamieSinn** [comment]
@Saphiria you may want to check your commit, looks a tad empty.
Unless you meant to make an issue :P

**Comment by ghost** [comment]
@JamieSinn Let me fix that. :+1:

**Comment by RoboMWM** [comment]
Sorry, was a rushed comment, mainly because I saw a blank commit so just guessed what it was. Seems fine I suppose. :+1:

**Comment by HappyHarm** [comment]
Looks nice :+1:

**Comment by ctian1** [comment]
Not sure if we need it. :-1:

**Comment by Nebhay** [comment]
:+1:

**Comment by ghost** [comment]
Please see this new PR. https://github.com/SpigotMC/SpigotCraft/pull/60

**Pull request closed without merging**
