### PR TITLE
Update AutoMessage for next upcoming major release.

### PR DESCRIPTION
**Pull request by yannicklamprecht**
Remove version number. => next upcoming major update

### CODE REVIEW

**Comment by stefvanschie** [comment]
There's a typo in your change: "upcomming" -> "upcoming".

**Comment by RedSpeeds** [comment]
Maybe change this into 1.16 release?

**Comment by yannicklamprecht** [comment]
> Maybe change this into 1.16 release?

Just why? Then we can use the other PR. 🤣 Formulating it so that it doesn't need to be changed in future.

**Comment by md-5** [comment]
Rephrased a bit differently, thanks c8ebd85816e7ca07478953fca9928d883998e700

**Pull request closed without merging**
