### PR TITLE
Basic essentials configuration.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by tavonkelly** [comment]
:+1:

**Comment by gsand** [comment]
:+1:

**Comment by KingFaris10** [comment]
;+1;

**Comment by dwi** [comment]
:+1: 
I would leave the enabledSigns with commented lines, tho.

**Comment by ctian1** [comment]
Inconsistent with PEX permissions.. in there builders are allowed to use Essentials signs and Essentials command permissions are already handled there.. however this config has no Essentials signs enabled and handles the default commands even though PEX already did.

**Comment by ghost** [comment]
@pangeacake which permissions ?????????? there are no permissions ????????????

**Comment by md-5** [comment]
Not needed, player-commands is overriden by permissions, the rest of the stuff is fine as is

**Pull request closed without merging**
