### PR TITLE
Adds Rotating Signs to the server.

### PR DESCRIPTION
**Pull request by LaxWasHere**
I am nice and have the necessary licenses for the plugin in the PR.

Resource page of said plugin: https://www.spigotmc.org/resources/signgis.50754/

Source of said plugin: https://github.com/AwesomePowered/SigngiS

Gif of said plugin: https://i.imgur.com/sBFHDxH.gifv

### CODE REVIEW

**Comment by yannicklamprecht** [comment]
https://github.com/AwesomePowered/SigngiS/blob/master/src/main/java/net/awesomepowered/signgis/SigngiS.java#L58-L70

Isn't that deprecated?

Why not using Directional?
Use https://hub.spigotmc.org/javadocs/spigot/org/bukkit/material/Directional.html#setFacingDirection-org.bukkit.block.BlockFace-

**Comment by MiniDigger** [comment]
@ysl3000 its open source, I am pretty sure lax appreciates PRs ;)

**Comment by 2008Choco** [comment]
To be completely honest, I'm not sure it matters. The MaterialData API is going to be outdated given that a new block state API is being added to Bukkit 1.13. I'm sure md_5 can correct me if I'm wrong, but MaterialData may even be deprecated as well come 1.13. Those data values will also remain in 1.13 but deprecated, so it causes no issues on the server afaik

**Comment by yannicklamprecht** [comment]
Only md-5 knows how it's done in the future.  Hope BlockStates expansion will come.

**Pull request merged**
