### PR TITLE
Update permissions.yml

### PR DESCRIPTION
**Pull request by wyatt-herkamp**
TPS and Timing's for the players.

### CODE REVIEW

**Comment by Banbeucmas** [comment]
Why not essentials.gc

**Comment by wyatt-herkamp** [comment]
I added that  @Banbeucmas 
Thank you.

**Comment by MiniDigger** [comment]
you guys should just be using irc :D

**Comment by wyatt-herkamp** [comment]
Updated to fix Merge issues.

**Comment by md-5** [comment]
No timings command please

**Comment by wyatt-herkamp** [comment]
Ok, I will remove that once I get power again.

**Comment by wyatt-herkamp** [comment]
Removed Timings as @md-5 suggested.

**Pull request merged**
