### PR TITLE
Disable PlotMe conversion

### PR DESCRIPTION
**Pull request by ghost**
Something tells me we have no need to try convert PlotMe.

### CODE REVIEW

**Comment by manuelgu** [comment]
:+1:

**Comment by RoboMWM** [comment]
Shouldn't matter.

**Comment by ghost** [comment]
:-1: -- Only because I see no reason.

**Comment by ghost** [comment]
Thing is, why not though? :P

**Comment by RoboMWM** [comment]
Probably because it won't convert since there's no plotme folder nor jar so it really doesn't matter

**Comment by ghost** [comment]
^

**Comment by ghost** [comment]
Just trying to keep things ordered...

**Comment by manuelgu** [comment]
> Just trying to keep things ordered...

I agree.

**Comment by ghost** [comment]
:+1:

**Comment by DoNotSpamPls** [comment]
:-1: I think this is useless

**Pull request closed without merging**
