### PR TITLE
Update motd.txt

### PR DESCRIPTION
**Pull request by ghost**
I have kept the color codes setup by @Cldfire, but I have changed the top row slightly, by adding a {PLAYER} tag.

Example: http://uploads.im/XcwdM.png

### CODE REVIEW

**Comment by Cldfire** [comment]
Looks good. :+1:

**Comment by ghost** [comment]
To see it in action: http://uploads.im/XcwdM.png

**Comment by ghost** [comment]
:+1:

**Comment by ghost** [comment]
:+1:

**Comment by DoNotSpamPls** [comment]
:+1:

**Pull request closed without merging**
