### PR TITLE
Add Dynmap

### PR DESCRIPTION
**Pull request by RoboMWM**
Not sure how the community will think of this but I'd like to see a map of SpigotCraft in some form.

Would be nice to copy a dynmap link and show others progress or where they are, or just to see what some people are up to or whatever. I've tweaked some of the settings to reduce rendering load and disabled chat. Might want to use an external webserver?

Feel free to suggest/PR to this branch any changes.

### CODE REVIEW

**Comment by Cldfire** [comment]
:+1:

**Comment by HappyHarm** [comment]
:+1:

**Comment by Cadiducho** [comment]
:+1:

**Comment by JamieSinn** [comment]
I don't suggest dynmap. Rather, use WorldBorder and do a map fill. Then, use Minecraft Overviewer to make the map.
https://github.com/overviewer/Minecraft-Overviewer/
It's much much better, and doesn't destroy the CPU (Okay, maybe while it's running, but not after.)
:-1: to dynmap, :+1: to map.

**Comment by ghost** [comment]
:-1: I'd suggest using `overviewer` alongside `worldborder` as @JamieSinn suggested.

**Comment by RoboMWM** [comment]
How often will we run that (if we do that)? I'm sure some would like to see progress of the map?

Or we could turn off rendering completely and only do periodic fullrenders.

**Comment by md-5** [comment]
Won't this blow up without nms?

**Comment by RoboMWM** [comment]
It uses NMS? Never knew about that...

**Comment by RoboMWM** [comment]
I guess so. https://github.com/webbukkit/dynmap/blob/master/src/main/java/org/dynmap/bukkit/BukkitVersionHelperGeneric.java#L129

**Pull request closed without merging**
