### PR TITLE
Gotta stop those unwanted connections to shitgot

### PR DESCRIPTION
**Pull request by MeltedLux**

### CODE REVIEW

**Comment by MeltedLux** [comment]
:+1:

**Comment by Sponges** [comment]
:+1:

**Comment by TitanicFreak** [comment]
:+1:

**Comment by Chnkr** [comment]
:-1:

**Comment by RenegadeEagle** [comment]
lux is my dad

**Comment by RenegadeEagle** [comment]
lux is my dad

**Comment by TheReverend403** [comment]
+1

**Pull request closed without merging**
