### PR TITLE
Add CoreProtect

### PR DESCRIPTION
**Pull request by Serializator**
As far as I know CoreProtect has the same and even more features than LogBlock.

### CODE REVIEW

**Comment by alaaeelsayed** [comment]
:+1:

**Comment by ghost** [comment]
they both do the same :-1:

**Comment by JamieSinn** [comment]
Logblock is much easier to use IMO. As well, much lighter on the DB load.
It's also the standard amongst servers.

**Comment by Serializator** [comment]
When @Chnkr told me that they both do the same I searched again but a different LogBlock came up which is indeed the same as CoreProject.

Probably a misspell on my side when I was searching, so for the inconvenience.

**Pull request closed without merging**
