### PR TITLE
FAQ Plugin

### PR DESCRIPTION
**Pull request by ghost**
This is a FAQ Plugin that will completely replace Essentials /info, /help, etc. I have used this many times and I love it, and I suggest you use it as well.

### CODE REVIEW

**Comment by HappyHarm** [comment]
:+1:

**Comment by ghost** [comment]
:+1:

**Comment by DoNotSpamPls** [comment]
:-1: I don't think we should overload the server with many plugins.
If Essentials can do it, let it do it.

**Comment by TomLewis** [comment]
:-1: 
All be done with Essentials, no need for a FAQ plugin. /info and /help and /customtext can both be edited using essentials.

**Comment by Cldfire** [comment]
:+1:
Excellent plugin, far better then /info.

**Pull request closed without merging**
