### PR TITLE
Create a Start Script I want to share.

### PR DESCRIPTION
**Pull request by KenaiTheWolf**
This script has a few features:
1. Uses NUMA 
2. The better G1GC is enabled
3. Bigger Heap sizes (less lag and load time)
4. You don't have to rename the spigot.jar file with every version, it will change directories to the directory it is in and search for any file containing the text "spigot" and ".jar" and then launch them, the text in between can be anything.

### CODE REVIEW

**Comment by RoboMWM** [comment]
Uh you should probably discuss with @Aikar some of your... decisions with your java flags.

**Comment by TomLewis** [comment]
Would you run this inside screen/tmux or would it be better to have a script outside of screen/tmux that manages the tmux/screen session?

**Comment by KenaiTheWolf** [comment]
These flags were as close as I could get it to 20 TPS with dynmap

**Comment by KenaiTheWolf** [comment]
Also I run the script on OS X without screen, because I have a plugin that just runs /stop on my server every 6hrs.

**Pull request closed without merging**
