### PR TITLE
Add Bedrock Support and ViaVersion.

### PR DESCRIPTION
**Pull request by Outfit8TSB**
add at least bedrock support and Older Version Support.

Why is it Necessary:
 i am a pure bedrock user and and i didn't buy java. 
you should know that both edition is different. also i have to login everytime i use Geyser-Standalone, but i don't have java. do you think that makes me happy? it doesn't.

also, lot of users uses old version to use mods.
and lot of popular servers allows lot of versions. look at these motds:
```
               -]----- SuperMC -----[-
            [1.7-LATEST] AWESOME SERVER!
```
Now You Know why this pull request is neccessary?
#BEDROCKLIVESMATTER
#OLDVERSIONLIVESMATTER

### CODE REVIEW

**Comment by radstevee** [comment]
Looks like you are mising the point of this server. It is a public testing server for snapshots and similar.

There's also barely anyone who actually plays on it.

**Comment by Outfit8TSB** [comment]
oh.

**Comment by Outfit8TSB** [comment]
Ok may i reopen this sir? 1.7 and Bedrock players might want to test the spigot snapshot out zir.

**Comment by The-Epic** [comment]
1.7 players cant see the latest snapshot content other than connectivity which would be waiting on via version to update and via version doesnt get the server snapshot so it wouldnt work, and bedrock would be the same thing

**Comment by Outfit8TSB** [comment]
D'oh!
(i wanted to play this server so bad.)

**Comment by Outfit8TSB** [comment]
This is why created the pull request.
I wanted to play here. acquiring spigotmc was a joke

**Comment by RaydanOMGr** [comment]
Excuse me what

**Comment by Outfit8TSB** [comment]
i was joking, i only want to play on that server.

**Comment by Outfit8TSB** [comment]
> 1.7 players cant see the latest snapshot content other than connectivity which would be waiting on via version to update and via version doesnt get the server snapshot so it wouldnt work, and bedrock would be the same thing

look, i just dont care and i want to play.

**Comment by Outfit8TSB** [comment]
> Looks like you are mising the point of this server. It is a public testing server for snapshots and similar.
> 
> There's also barely anyone who actually plays on it.

i just dont care, i wnat to play play.spigotmc.org and run /ver command to see what is like

**Comment by The-Epic** [comment]
Didnt you send md_5 to jail, why do you want to play his server

**Pull request closed without merging**
