### PR TITLE
The ~ before someones name doesn't look very nice.

### PR DESCRIPTION
**Pull request by HappyHarm**

### CODE REVIEW

**Comment by SilverCory** [comment]
:+1: I'd suggest changing it to a period. It's discreet but allows people to know it's not their actual user.

**Comment by HappyHarm** [comment]
Or maybe use Italic for it? Then you don't have anyhing before your name.

**Comment by Maximvdw** [comment]
:+1: Im pro for not it being a ~ but :-1: for it being italic or a period

Maybe something original?

**Comment by SilverCory** [comment]
Oh I know, lets have 'NICKNAME HERE BETCH'.. Something clean and discreet in my opinion. The period fits all needs for that. &k might fit? xD

**Comment by JamieSinn** [comment]
I've seen *\* used nicely

**Comment by HeroCC** [comment]
:+1: for the Italics

**Comment by HappyHarm** [comment]
Maybe just another color for when you use a nickname? I don't know or there will be any donator ranks or someone like that?

**Comment by 0x277F** [comment]
I don't see why nicknames would be used very much - I do have an idea though. Maybe a nickname could be automatically assigned based on your forum account name. In this case, the prefix should be removed entirely.

**Comment by SilverCory** [comment]
^^^ THIS! It would help tonnes. :+1:

**Comment by ghost** [comment]
:+1: to @0x277F's suggestion.

**Pull request closed without merging**
